name: Test ADClock Server

# Controls when the action will run. 
on: 
  push:

  workflow_dispatch:

# Runs all tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      #
      # Download and install all needed 
      #
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
        
      #
      # Caching for speedup
      #
      - name: Gradle Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    
      #
      # Testing
      #
      - name: Test with Gradle
        run: gradle test
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          
