name: ADClock Server Release CI

# Controls when the action will run. 
on: 
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      #
      # Download and install all needed 
      #
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      #
      # Caching for speedup
      #
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    
      #
      # Testing
      #
      - name: Test with Gradle
        run: gradle test
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          
